/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_MaTenLoai;
import BLL.BLL_PhieuChi;
import BLL.BLL_TaiKhoan;
import DAL.DAL_PhieuChi;
import DTO.DTO_HangMucChi;
import DTO.DTO_PhieuChi;
import DTO.DTO_PhuongThucThanhToan;
import static GUI.GUI_pnl_QuanLiChiPhi.pnlFormChinh;
import HELPER.HELPER_ChuyenDoi;
import HELPER.HELPER_SetMa;
import HELPER.HELPER_Validate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author CherryCe
 */
public class GUI_dal_PhieuChi extends javax.swing.JDialog {

    public boolean isDelete = false;

    /**
     * Creates new form GUI_dalThongTinPhong
     */
    public GUI_dal_PhieuChi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadMucChi();
        loadPhuongThuc();
        check();
        validation();
    }
    
    public void validation() {
        if (!GUI_frm_Menu.auThenTiCaTion()) {
            lblXoa.setVisible(false);
        }
        return;
    }

    public void check() {
        if (GUI_pnl_ChiTietPhieuChi.isPhieuChi) {
            loadChiTiet();
            lblThanhToan.setVisible(false);
            isDelete = true;
            GUI_pnl_ChiTietPhieuChi.isPhieuChi = false;
        } else {
            load();
            lblThanhToan.setVisible(true);
            isDelete = false;
            GUI_pnl_ChiTietPhieuChi.isPhieuChi = false;
        }
    }

    public void add() {
        DTO_PhieuChi phieuChi = new DTO_PhieuChi(lblSetMaPhieu.getText(), String.valueOf(cboMucChi.getSelectedItem()), HELPER_ChuyenDoi.getSoInt(txtTongTien.getText()), String.valueOf(cboPhuongThuc.getSelectedItem()), txtGhiChu.getText(), HELPER_ChuyenDoi.getNgayDate("dd-MM-yy HH:mm", lblSetNgayTao.getText()), lblSetNhanVien.getText());
        BLL_PhieuChi.add(phieuChi);
    }

    public void delete() {
        int choice = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xóa Không ?", "Xóa", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            String maPhieuChi = lblSetMaPhieu.getText();
            BLL_PhieuChi.delete(maPhieuChi);
        }
        return;
    }

    public void loadChiTiet() {
        ArrayList<DTO_PhieuChi> array = BLL_PhieuChi.search(GUI_pnl_QuanLiChiPhi.tuNgay, GUI_pnl_QuanLiChiPhi.denNgay, GUI_pnl_ChiTietPhieuChi.indexPosition + 1);
        BLL_PhieuChi.loadChiTiet(array, lblSetMaPhieu, cboMucChi, txtTongTien, cboPhuongThuc, txtGhiChu, lblSetNgayTao, lblSetNhanVien);
    }

    public void load() {
        lblSetNhanVien.setText(BLL_MaTenLoai.findTenNhanVien(BLL_TaiKhoan.selectMaNhanVien(GUI_pnl_DangNhap.taiKhoan)));
        lblSetMaPhieu.setText(HELPER_SetMa.setMaDateTime("MC"));
        lblSetNgayTao.setText(HELPER_ChuyenDoi.getTimeNow("dd-MM-yy HH:mm"));
    }

    public void loadMucChi() {
        ArrayList<DTO_HangMucChi> arrayMucChi = BLL_MaTenLoai.selectTenMucChi();
        BLL_MaTenLoai.loadTenMucChi(arrayMucChi, cboMucChi);
    }

    public void loadPhuongThuc() {
        ArrayList<DTO_PhuongThucThanhToan> arrayPhuongThuc = BLL_MaTenLoai.selectTenPhuongThuc();
        BLL_MaTenLoai.loadTenPhuongThuc(arrayPhuongThuc, cboPhuongThuc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoChucNang = new HELPER.PanelShadow();
        lblThoat = new javax.swing.JLabel();
        lblThanhToan = new javax.swing.JLabel();
        lblXoa = new javax.swing.JLabel();
        sdoPhieuChi = new HELPER.PanelShadow();
        lblNgayTao = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        lblMucChi = new javax.swing.JLabel();
        lblPhieuChi = new javax.swing.JLabel();
        lblSetMaPhieu = new javax.swing.JLabel();
        lblMaPhieu = new javax.swing.JLabel();
        lblPhuongThuc = new javax.swing.JLabel();
        lblSetNhanVien = new javax.swing.JLabel();
        lblSetNgayTao = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        cboMucChi = new javax.swing.JComboBox<>();
        cboPhuongThuc = new javax.swing.JComboBox<>();
        spt_1 = new javax.swing.JSeparator();
        lblExit = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(420, 340));
        setUndecorated(true);

        sdoChucNang.setBackground(new java.awt.Color(255, 255, 255));
        sdoChucNang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(33, 150, 243)));
        sdoChucNang.setMinimumSize(new java.awt.Dimension(420, 60));
        sdoChucNang.setPreferredSize(new java.awt.Dimension(420, 60));
        sdoChucNang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThoat.setBackground(new java.awt.Color(255, 255, 255));
        lblThoat.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(33, 150, 243));
        lblThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout (6).png"))); // NOI18N
        lblThoat.setText("Thoát");
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        sdoChucNang.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 80, 40));

        lblThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        lblThanhToan.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblThanhToan.setForeground(new java.awt.Color(33, 150, 243));
        lblThanhToan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cart (3).png"))); // NOI18N
        lblThanhToan.setText("Thanh Toán");
        lblThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThanhToanMouseClicked(evt);
            }
        });
        sdoChucNang.add(lblThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 120, 40));

        lblXoa.setBackground(new java.awt.Color(255, 255, 255));
        lblXoa.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblXoa.setForeground(new java.awt.Color(33, 150, 243));
        lblXoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/delete.png"))); // NOI18N
        lblXoa.setText("Xóa");
        lblXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXoaMouseClicked(evt);
            }
        });
        lblXoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblXoaKeyPressed(evt);
            }
        });
        sdoChucNang.add(lblXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 70, 40));

        sdoPhieuChi.setBackground(new java.awt.Color(255, 255, 255));
        sdoPhieuChi.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(33, 150, 243)));
        sdoPhieuChi.setMinimumSize(new java.awt.Dimension(420, 280));
        sdoPhieuChi.setPreferredSize(new java.awt.Dimension(420, 280));
        sdoPhieuChi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNgayTao.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayTao.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayTao.setForeground(new java.awt.Color(153, 153, 153));
        lblNgayTao.setText("Ngày Tạo");
        sdoPhieuChi.add(lblNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 70, -1));

        lblNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblNhanVien.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(153, 153, 153));
        lblNhanVien.setText("Nhân Viên");
        sdoPhieuChi.add(lblNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, -1));

        lblGhiChu.setBackground(new java.awt.Color(255, 255, 255));
        lblGhiChu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(153, 153, 153));
        lblGhiChu.setText("Ghi Chú");
        sdoPhieuChi.add(lblGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 50, 20));

        lblMucChi.setBackground(new java.awt.Color(255, 255, 255));
        lblMucChi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMucChi.setForeground(new java.awt.Color(153, 153, 153));
        lblMucChi.setText("Mục Chi");
        sdoPhieuChi.add(lblMucChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, 20));

        lblPhieuChi.setBackground(new java.awt.Color(255, 255, 255));
        lblPhieuChi.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblPhieuChi.setForeground(new java.awt.Color(62, 73, 95));
        lblPhieuChi.setText("PHIẾU CHI");
        sdoPhieuChi.add(lblPhieuChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        lblSetMaPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblSetMaPhieu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetMaPhieu.setForeground(new java.awt.Color(62, 73, 95));
        sdoPhieuChi.add(lblSetMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 100, 20));

        lblMaPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblMaPhieu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaPhieu.setForeground(new java.awt.Color(153, 153, 153));
        lblMaPhieu.setText("Mã Phiếu");
        sdoPhieuChi.add(lblMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, 20));

        lblPhuongThuc.setBackground(new java.awt.Color(255, 255, 255));
        lblPhuongThuc.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblPhuongThuc.setForeground(new java.awt.Color(153, 153, 153));
        lblPhuongThuc.setText("Phương Thức");
        sdoPhieuChi.add(lblPhuongThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 20));

        lblSetNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNhanVien.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetNhanVien.setForeground(new java.awt.Color(62, 73, 95));
        sdoPhieuChi.add(lblSetNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, 20));

        lblSetNgayTao.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetNgayTao.setForeground(new java.awt.Color(62, 73, 95));
        sdoPhieuChi.add(lblSetNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, 20));

        lblTongTien.setBackground(new java.awt.Color(255, 255, 255));
        lblTongTien.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(153, 153, 153));
        lblTongTien.setText("Tổng Tiền");
        sdoPhieuChi.add(lblTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, 20));

        txtTongTien.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtTongTien.setForeground(new java.awt.Color(62, 73, 95));
        txtTongTien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTongTien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTongTienFocusLost(evt);
            }
        });
        txtTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongTienActionPerformed(evt);
            }
        });
        txtTongTien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTongTienKeyReleased(evt);
            }
        });
        sdoPhieuChi.add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 70, 20));

        txtGhiChu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(62, 73, 95));
        txtGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });
        sdoPhieuChi.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 300, 20));

        cboMucChi.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboMucChi.setForeground(new java.awt.Color(62, 73, 95));
        cboMucChi.setToolTipText("");
        cboMucChi.setBorder(null);
        sdoPhieuChi.add(cboMucChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 20));

        cboPhuongThuc.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboPhuongThuc.setForeground(new java.awt.Color(62, 73, 95));
        cboPhuongThuc.setToolTipText("");
        cboPhuongThuc.setBorder(null);
        sdoPhieuChi.add(cboPhuongThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 110, 20));
        sdoPhieuChi.add(spt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 380, 10));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close (1).png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        sdoPhieuChi.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoPhieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sdoChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sdoPhieuChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sdoChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongTienActionPerformed

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lblThoatMouseClicked

    private void lblThanhToanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThanhToanMouseClicked
        // TODO add your handling code here:
        add();
        GUI_pnl_QuanLiChiPhi.search();
        dispose();
    }//GEN-LAST:event_lblThanhToanMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXoaMouseClicked
        // TODO add your handling code here:
        if (isDelete) {
            delete();
            GUI_pnl_QuanLiChiPhi.search();
            dispose();
        }
        return;
    }//GEN-LAST:event_lblXoaMouseClicked

    private void lblXoaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblXoaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblXoaKeyPressed

    private void txtTongTienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTongTienKeyReleased
        // TODO add your handling code here:
        HELPER_Validate.validateNumber(txtTongTien);
    }//GEN-LAST:event_txtTongTienKeyReleased

    private void txtTongTienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTongTienFocusLost
        // TODO add your handling code here:
        txtTongTien.setText(txtTongTien.getText() + "K");
    }//GEN-LAST:event_txtTongTienFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_PhieuChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_PhieuChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_PhieuChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_PhieuChi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI_dal_PhieuChi dialog = new GUI_dal_PhieuChi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboMucChi;
    private javax.swing.JComboBox<String> cboPhuongThuc;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblMaPhieu;
    private javax.swing.JLabel lblMucChi;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblPhieuChi;
    private javax.swing.JLabel lblPhuongThuc;
    private javax.swing.JLabel lblSetMaPhieu;
    private javax.swing.JLabel lblSetNgayTao;
    private javax.swing.JLabel lblSetNhanVien;
    private javax.swing.JLabel lblThanhToan;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblXoa;
    private HELPER.PanelShadow sdoChucNang;
    private HELPER.PanelShadow sdoPhieuChi;
    private javax.swing.JSeparator spt_1;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
