/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_DichVu;
import BLL.BLL_MaTenLoai;
import BLL.BLL_Phong;
import BLL.BLL_SanPham;
import BLL.BLL_ThuePhong;
import DTO.DTO_Phong;
import DTO.DTO_SanPham;
import DTO.DTO_ThuePhong;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_ChonPhong extends javax.swing.JPanel {

    public static int indexPosition;

    /**
     * Creates new form GUI_pnl_ChonPhong
     */
    public GUI_pnl_ChonPhong() {
        initComponents();
        load();
    }

    public void load() {
        ArrayList<DTO_Phong> array = BLL_Phong.searchChonPhong(GUI_dal_ChonPhong.maTang, GUI_dal_ChonPhong.index);
        BLL_Phong.loadChonPhong(array, lblSoPhong, lblSetTrangThai);
        if (lblSetTrangThai.getText().equals("Có Khách")) {
            pnlChonPhong.setBackground(new Color(255, 142, 113));
        } else if (lblSetTrangThai.getText().equals("Đặt Trước")) {
            pnlChonPhong.setBackground(new Color(102, 153, 255));
        }
    }

    public void loadPhong() {
        ArrayList<DTO_ThuePhong> array = BLL_Phong.searchSoPhong(GUI_dal_ChonPhong.maTang, indexPosition + 1);
        BLL_Phong.loadSoPhong(array, GUI_dal_ThongTinDichVu.lblSetSoPhong, GUI_dal_ThongTinDichVu.lblSetNgayDen, GUI_dal_ThongTinDichVu.lblSetNgayDi);
        GUI_dal_ChonPhong.dal.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChonPhong = new javax.swing.JPanel();
        lblSoPhong = new javax.swing.JLabel();
        lblSetTrangThai = new javax.swing.JLabel();
        lblIconTrangThai = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(150, 100));

        pnlChonPhong.setBackground(new java.awt.Color(97, 177, 90));
        pnlChonPhong.setMinimumSize(new java.awt.Dimension(150, 100));
        pnlChonPhong.setPreferredSize(new java.awt.Dimension(150, 100));
        pnlChonPhong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlChonPhongMouseMoved(evt);
            }
        });
        pnlChonPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlChonPhongMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlChonPhongMouseExited(evt);
            }
        });
        pnlChonPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSoPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblSoPhong.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblSoPhong.setForeground(new java.awt.Color(255, 255, 255));
        pnlChonPhong.add(lblSoPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        lblSetTrangThai.setBackground(new java.awt.Color(255, 255, 255));
        lblSetTrangThai.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetTrangThai.setForeground(new java.awt.Color(255, 255, 255));
        lblSetTrangThai.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pnlChonPhong.add(lblSetTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 20));

        lblIconTrangThai.setBackground(new java.awt.Color(255, 255, 255));
        lblIconTrangThai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hotel-sign (2).png"))); // NOI18N
        pnlChonPhong.add(lblIconTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChonPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChonPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlChonPhongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChonPhongMouseMoved
        // TODO add your handling code here:
        pnlChonPhong.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(33, 150, 243)));
    }//GEN-LAST:event_pnlChonPhongMouseMoved

    private void pnlChonPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChonPhongMouseExited
        // TODO add your handling code here:
        pnlChonPhong.setBorder(null);
    }//GEN-LAST:event_pnlChonPhongMouseExited

    private void pnlChonPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChonPhongMouseClicked
        // TODO add your handling code here:
        indexPosition = GUI_dal_ChonPhong.pnlDanhSachPhong.getComponentZOrder(pnlChonPhong);
        loadPhong();
    }//GEN-LAST:event_pnlChonPhongMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblIconTrangThai;
    private javax.swing.JLabel lblSetTrangThai;
    private javax.swing.JLabel lblSoPhong;
    public javax.swing.JPanel pnlChonPhong;
    // End of variables declaration//GEN-END:variables
}
