/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_DichVu;
import BLL.BLL_MaTenLoai;
import BLL.BLL_Phong;
import BLL.BLL_SanPham;
import BLL.BLL_ThuePhong;
import DTO.DTO_Phong;
import DTO.DTO_SanPham;
import DTO.DTO_ThuePhong;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_ChuyenPhong extends javax.swing.JPanel {

    public static int indexPosition;

    /**
     * Creates new form GUI_pnl_ChonPhong
     */
    public GUI_pnl_ChuyenPhong() {
        initComponents();
        load();
    }

    public void load() {
        ArrayList<DTO_Phong> array = BLL_Phong.searchChuyenPhong(GUI_dal_ChuyenPhong.maTang, GUI_dal_ChuyenPhong.index);
        BLL_Phong.loadChuyenPhong(array, lblSoPhong, lblSetLoaiPhong);
    }

    public void loadPhong() {
        GUI_dal_ChuyenPhong.lblSoPhongDen.setText(BLL_Phong.selectChuyenPhong(GUI_dal_ChuyenPhong.maTang, indexPosition + 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChuyenPhong = new javax.swing.JPanel();
        lblSoPhong = new javax.swing.JLabel();
        lblSetLoaiPhong = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(150, 100));

        pnlChuyenPhong.setBackground(new java.awt.Color(97, 177, 90));
        pnlChuyenPhong.setMinimumSize(new java.awt.Dimension(150, 100));
        pnlChuyenPhong.setPreferredSize(new java.awt.Dimension(150, 100));
        pnlChuyenPhong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pnlChuyenPhongMouseMoved(evt);
            }
        });
        pnlChuyenPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlChuyenPhongMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlChuyenPhongMouseExited(evt);
            }
        });
        pnlChuyenPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSoPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblSoPhong.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblSoPhong.setForeground(new java.awt.Color(255, 255, 255));
        pnlChuyenPhong.add(lblSoPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 20));

        lblSetLoaiPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblSetLoaiPhong.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetLoaiPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblSetLoaiPhong.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pnlChuyenPhong.add(lblSetLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChuyenPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChuyenPhong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pnlChuyenPhongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChuyenPhongMouseMoved
        // TODO add your handling code here:
        pnlChuyenPhong.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(33, 150, 243)));
    }//GEN-LAST:event_pnlChuyenPhongMouseMoved

    private void pnlChuyenPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChuyenPhongMouseExited
        // TODO add your handling code here:
        pnlChuyenPhong.setBorder(null);
    }//GEN-LAST:event_pnlChuyenPhongMouseExited

    private void pnlChuyenPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlChuyenPhongMouseClicked
        // TODO add your handling code here:
        indexPosition = GUI_dal_ChuyenPhong.pnlDanhSachPhong.getComponentZOrder(pnlChuyenPhong);
        loadPhong();
    }//GEN-LAST:event_pnlChuyenPhongMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblSetLoaiPhong;
    private javax.swing.JLabel lblSoPhong;
    public javax.swing.JPanel pnlChuyenPhong;
    // End of variables declaration//GEN-END:variables
}
