/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_HangMucChi;
import BLL.BLL_MaTenLoai;
import BLL.BLL_Phong;
import DTO.DTO_HangMucChi;
import DTO.DTO_SoTang;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author CherryCe
 */
public class GUI_dal_ChonPhong extends javax.swing.JDialog {

    public static String maTang;
    public static int index;
    public static int setHeight;
    public static JDialog dal = null;

    /**
     * Creates new form GUI_dalThongTinPhong
     */
    public GUI_dal_ChonPhong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadTenTang();
        search();
        dal = this;
    }

    public void loadTenTang() {
        ArrayList<DTO_SoTang> array = BLL_MaTenLoai.selectTenTang();
        BLL_MaTenLoai.loadTenTang(array, cboTang);
    }

    public void search() {
        if (BLL_Phong.countSearchChonPhong(maTang) % 4 == 0) {
            setHeight = BLL_Phong.countSearchChonPhong(maTang) / 4;
        } else {
            setHeight = (BLL_Phong.countSearchChonPhong(maTang) / 4) + 1;
        }
        pnlDanhSachPhong.setPreferredSize(new Dimension(710, 150 * setHeight));
        pnlDanhSachPhong.removeAll();
        for (int i = 1; i <= BLL_Phong.countSearchChonPhong(maTang); i++) {
            index = i;
            pnlDanhSachPhong.add(new GUI_pnl_ChonPhong().pnlChonPhong);
        }
        pnlDanhSachPhong.validate();
        pnlDanhSachPhong.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoDanhSachPhong = new HELPER.PanelShadow();
        lblChonPhong = new javax.swing.JLabel();
        cboTang = new javax.swing.JComboBox<>();
        lblExit = new javax.swing.JLabel();
        scrDanhSachPhong = new javax.swing.JScrollPane();
        pnlDanhSachPhong = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 450));
        setUndecorated(true);

        sdoDanhSachPhong.setBackground(new java.awt.Color(255, 255, 255));
        sdoDanhSachPhong.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(33, 150, 243)));
        sdoDanhSachPhong.setMinimumSize(new java.awt.Dimension(750, 450));
        sdoDanhSachPhong.setPreferredSize(new java.awt.Dimension(750, 450));
        sdoDanhSachPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChonPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblChonPhong.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblChonPhong.setForeground(new java.awt.Color(62, 73, 95));
        lblChonPhong.setText("CHỌN PHÒNG");
        sdoDanhSachPhong.add(lblChonPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, 130, 30));

        cboTang.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboTang.setForeground(new java.awt.Color(62, 73, 95));
        cboTang.setToolTipText("");
        cboTang.setBorder(null);
        cboTang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTangItemStateChanged(evt);
            }
        });
        sdoDanhSachPhong.add(cboTang, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 16, 100, -1));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close (1).png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        sdoDanhSachPhong.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 30, 30));

        scrDanhSachPhong.setBackground(new java.awt.Color(255, 255, 255));
        scrDanhSachPhong.setBorder(null);
        scrDanhSachPhong.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlDanhSachPhong.setBackground(new java.awt.Color(255, 255, 255));
        pnlDanhSachPhong.setMinimumSize(new java.awt.Dimension(710, 380));
        pnlDanhSachPhong.setPreferredSize(new java.awt.Dimension(710, 380));
        pnlDanhSachPhong.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20));
        scrDanhSachPhong.setViewportView(pnlDanhSachPhong);

        sdoDanhSachPhong.add(scrDanhSachPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 710, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoDanhSachPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoDanhSachPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void cboTangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTangItemStateChanged
        // TODO add your handling code here:
        maTang = BLL_MaTenLoai.findMaTang(String.valueOf(cboTang.getSelectedItem()));
        search();
    }//GEN-LAST:event_cboTangItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ChonPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ChonPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ChonPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ChonPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI_dal_ChonPhong dialog = new GUI_dal_ChonPhong(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboTang;
    private javax.swing.JLabel lblChonPhong;
    private javax.swing.JLabel lblExit;
    public static javax.swing.JPanel pnlDanhSachPhong;
    private javax.swing.JScrollPane scrDanhSachPhong;
    private HELPER.PanelShadow sdoDanhSachPhong;
    // End of variables declaration//GEN-END:variables
}
