/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_HangMucChi;
import BLL.BLL_HoaDon;
import BLL.BLL_MaTenLoai;
import BLL.BLL_PhuongThucThanhToan;
import BLL.BLL_TaiKhoan;
import DAL.DAL_DichVu;
import DTO.DTO_HangMucChi;
import DTO.DTO_HoaDon;
import DTO.DTO_PhuongThucThanhToan;
import HELPER.HELPER_ChuyenDoi;
import HELPER.HELPER_ConnectSQL;
import HELPER.HELPER_SetMa;
import java.util.ArrayList;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author CherryCe
 */
public class GUI_dal_ThanhToan extends javax.swing.JDialog {

    /**
     * Creates new form GUI_dalThongTinPhong
     */
    public GUI_dal_ThanhToan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        load();
        phuongThucThanhToan();
    }
    
    public void load() {
        lblSetSoPhong.setText(GUI_dal_ThongTinPhong.lblSetSoPhong.getText());
        lblSetTienPhong.setText(HELPER_ChuyenDoi.getSoString(HELPER_ChuyenDoi.getSoInt(GUI_dal_ThongTinPhong.lblSetGiaPhong.getText()) - HELPER_ChuyenDoi.getSoInt(GUI_dal_ThongTinPhong.txtGiamGia.getText())) + "K");
        lblSetDichVu.setText(GUI_dal_ThongTinPhong.lblSetDichVu.getText());
        lblSetDatCoc.setText(GUI_dal_ThongTinPhong.txtTienCoc.getText());
        lblSetThanhToan.setText(GUI_dal_ThongTinPhong.lblSetThanhToan.getText());
        lblSetConLai.setText(GUI_dal_ThongTinPhong.lblSetConLai.getText());
        lblSetMaPhieu.setText(HELPER_SetMa.setMaDateTime("HD"));
        lblSetNhanVien.setText(BLL_MaTenLoai.findTenNhanVien(BLL_TaiKhoan.selectMaNhanVien(GUI_pnl_DangNhap.taiKhoan)));
        lblSetNgayTao.setText(HELPER_ChuyenDoi.getTimeNow("dd-MM-yy HH:mm"));
    }
    
    public void phuongThucThanhToan() {
        ArrayList<DTO_PhuongThucThanhToan> arrayPhuongThuc = BLL_PhuongThucThanhToan.select();
        BLL_PhuongThucThanhToan.load(arrayPhuongThuc, cboPhuongThuc);
    }
    
    public void xuatHoaDon(String maHoaDon) {
        try {
            Hashtable map = new Hashtable();
            JasperReport report = JasperCompileManager.compileReport("src/GUI/GUI_rpt_HoaDon.jrxml");
            map.put("MaHoaDon", maHoaDon);
            JasperPrint p = JasperFillManager.fillReport(report, map, HELPER_ConnectSQL.conn);
            JasperViewer.viewReport(p, false);
            JasperExportManager.exportReportToPdfFile(p, "HoaDon.pdf");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoThanhToan = new HELPER.PanelShadow();
        lblMaPhieu = new javax.swing.JLabel();
        lblSoPhong = new javax.swing.JLabel();
        lblSetNgayTao = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblThanhToan = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblDichVu = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        lblSetMaPhieu = new javax.swing.JLabel();
        lblSetSoPhong = new javax.swing.JLabel();
        spt_1 = new javax.swing.JSeparator();
        lblConLai = new javax.swing.JLabel();
        lblDatCoc = new javax.swing.JLabel();
        lblDaThanhToan = new javax.swing.JLabel();
        lblPhuongThuc = new javax.swing.JLabel();
        lblSetNhanVien = new javax.swing.JLabel();
        lblSetConLai = new javax.swing.JLabel();
        lblSetTienPhong = new javax.swing.JLabel();
        lblTienPhong = new javax.swing.JLabel();
        cboPhuongThuc = new javax.swing.JComboBox<>();
        lblSetDichVu = new javax.swing.JLabel();
        lblSetDatCoc = new javax.swing.JLabel();
        lblSetThanhToan = new javax.swing.JLabel();
        sdoChucNang = new HELPER.PanelShadow();
        lblThoat = new javax.swing.JLabel();
        lblInPhieu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(600, 400));
        setUndecorated(true);

        sdoThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        sdoThanhToan.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(33, 150, 243)));
        sdoThanhToan.setMinimumSize(new java.awt.Dimension(600, 350));
        sdoThanhToan.setPreferredSize(new java.awt.Dimension(600, 350));
        sdoThanhToan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblMaPhieu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaPhieu.setForeground(new java.awt.Color(153, 153, 153));
        lblMaPhieu.setText("Mã Phiếu");
        sdoThanhToan.add(lblMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 60, 20));

        lblSoPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblSoPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSoPhong.setForeground(new java.awt.Color(153, 153, 153));
        lblSoPhong.setText("Số Phòng");
        sdoThanhToan.add(lblSoPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, 20));

        lblSetNgayTao.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetNgayTao.setForeground(new java.awt.Color(62, 73, 95));
        sdoThanhToan.add(lblSetNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 100, 20));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close (1).png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        sdoThanhToan.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 30, 30));

        lblThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        lblThanhToan.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblThanhToan.setForeground(new java.awt.Color(62, 73, 95));
        lblThanhToan.setText("THANH TOÁN");
        sdoThanhToan.add(lblThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        lblNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblNhanVien.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(153, 153, 153));
        lblNhanVien.setText("Nhân Viên");
        sdoThanhToan.add(lblNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 70, 20));

        lblDichVu.setBackground(new java.awt.Color(255, 255, 255));
        lblDichVu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDichVu.setForeground(new java.awt.Color(153, 153, 153));
        lblDichVu.setText("Dịch Vụ");
        sdoThanhToan.add(lblDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 50, 20));

        lblNgayTao.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayTao.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayTao.setForeground(new java.awt.Color(153, 153, 153));
        lblNgayTao.setText("Ngày Tạo");
        sdoThanhToan.add(lblNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 60, -1));

        lblSetMaPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblSetMaPhieu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetMaPhieu.setForeground(new java.awt.Color(62, 73, 95));
        sdoThanhToan.add(lblSetMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 120, 20));

        lblSetSoPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblSetSoPhong.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetSoPhong.setForeground(new java.awt.Color(62, 73, 95));
        sdoThanhToan.add(lblSetSoPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 130, 20));
        sdoThanhToan.add(spt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 580, 10));

        lblConLai.setBackground(new java.awt.Color(255, 255, 255));
        lblConLai.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblConLai.setForeground(new java.awt.Color(153, 153, 153));
        lblConLai.setText("Còn Lại");
        sdoThanhToan.add(lblConLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 50, 20));

        lblDatCoc.setBackground(new java.awt.Color(255, 255, 255));
        lblDatCoc.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDatCoc.setForeground(new java.awt.Color(153, 153, 153));
        lblDatCoc.setText("Đặt Cọc");
        sdoThanhToan.add(lblDatCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 50, 20));

        lblDaThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        lblDaThanhToan.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDaThanhToan.setForeground(new java.awt.Color(153, 153, 153));
        lblDaThanhToan.setText("Đã Thanh Toán");
        sdoThanhToan.add(lblDaThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 90, 20));

        lblPhuongThuc.setBackground(new java.awt.Color(255, 255, 255));
        lblPhuongThuc.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblPhuongThuc.setForeground(new java.awt.Color(153, 153, 153));
        lblPhuongThuc.setText("Phương Thức ");
        sdoThanhToan.add(lblPhuongThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 90, 20));

        lblSetNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNhanVien.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetNhanVien.setForeground(new java.awt.Color(62, 73, 95));
        sdoThanhToan.add(lblSetNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 100, 20));

        lblSetConLai.setBackground(new java.awt.Color(255, 255, 255));
        lblSetConLai.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetConLai.setForeground(new java.awt.Color(255, 102, 102));
        sdoThanhToan.add(lblSetConLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 50, 20));

        lblSetTienPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblSetTienPhong.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetTienPhong.setForeground(new java.awt.Color(97, 177, 90));
        sdoThanhToan.add(lblSetTienPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 50, 20));

        lblTienPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblTienPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTienPhong.setForeground(new java.awt.Color(153, 153, 153));
        lblTienPhong.setText("Tiền Phòng");
        sdoThanhToan.add(lblTienPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 70, 20));

        cboPhuongThuc.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboPhuongThuc.setForeground(new java.awt.Color(62, 73, 95));
        cboPhuongThuc.setBorder(null);
        sdoThanhToan.add(cboPhuongThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 100, 20));

        lblSetDichVu.setBackground(new java.awt.Color(255, 255, 255));
        lblSetDichVu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetDichVu.setForeground(new java.awt.Color(97, 177, 90));
        sdoThanhToan.add(lblSetDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 50, 20));

        lblSetDatCoc.setBackground(new java.awt.Color(255, 255, 255));
        lblSetDatCoc.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetDatCoc.setForeground(new java.awt.Color(255, 102, 102));
        sdoThanhToan.add(lblSetDatCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 50, 20));

        lblSetThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        lblSetThanhToan.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetThanhToan.setForeground(new java.awt.Color(97, 177, 90));
        sdoThanhToan.add(lblSetThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 50, 20));

        sdoChucNang.setBackground(new java.awt.Color(255, 255, 255));
        sdoChucNang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(33, 150, 243)));
        sdoChucNang.setMinimumSize(new java.awt.Dimension(600, 50));
        sdoChucNang.setPreferredSize(new java.awt.Dimension(600, 50));
        sdoChucNang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThoat.setBackground(new java.awt.Color(255, 255, 255));
        lblThoat.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(33, 150, 243));
        lblThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout (6).png"))); // NOI18N
        lblThoat.setText("Thoát");
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        sdoChucNang.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 80, 30));

        lblInPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblInPhieu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblInPhieu.setForeground(new java.awt.Color(33, 150, 243));
        lblInPhieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bill (3).png"))); // NOI18N
        lblInPhieu.setText("In Phiếu");
        lblInPhieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInPhieuMouseClicked(evt);
            }
        });
        sdoChucNang.add(lblInPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sdoChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sdoThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sdoChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lblThoatMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblInPhieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInPhieuMouseClicked
        // TODO add your handling code here:
        GUI_dal_ThongTinPhong.addThanhToan();
        DTO_HoaDon hoaDon = new DTO_HoaDon(lblSetMaPhieu.getText(), GUI_dal_ThongTinPhong.lblSetMaPhieuThue.getText(), HELPER_ChuyenDoi.getNgayDate("dd-MM-yy HH:mm", lblSetNgayTao.getText()), BLL_MaTenLoai.findMaNhanVien(lblSetNhanVien.getText()), HELPER_ChuyenDoi.getSoInt(lblSetTienPhong.getText()), HELPER_ChuyenDoi.getSoInt(lblSetDichVu.getText()), HELPER_ChuyenDoi.getSoInt(lblSetDatCoc.getText()) + HELPER_ChuyenDoi.getSoInt(lblSetThanhToan.getText()), HELPER_ChuyenDoi.getSoInt(lblSetConLai.getText()), BLL_MaTenLoai.findMaPhuongThuc(String.valueOf(cboPhuongThuc.getSelectedItem())));
        BLL_HoaDon.addHoaDon(hoaDon);
        DAL_DichVu.setThanhToanByThuePhong(GUI_dal_ThongTinPhong.lblSetMaPhieuThue.getText());
        JOptionPane.showMessageDialog(this, "Thanh Toán Thành Công !!!");
        if (!GUI_pnl_SoDoPhong.isSelectPhong) {
            GUI_pnl_SoDoPhong.load();
        } else {
            GUI_pnl_SoDoPhong.search();
        }
        xuatHoaDon(lblSetMaPhieu.getText());
        GUI_dal_ThongTinPhong.dal.dispose();
        dispose();
    }//GEN-LAST:event_lblInPhieuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI_dal_ThanhToan dialog = new GUI_dal_ThanhToan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboPhuongThuc;
    private javax.swing.JLabel lblConLai;
    private javax.swing.JLabel lblDaThanhToan;
    private javax.swing.JLabel lblDatCoc;
    private javax.swing.JLabel lblDichVu;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblInPhieu;
    private javax.swing.JLabel lblMaPhieu;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblPhuongThuc;
    private javax.swing.JLabel lblSetConLai;
    private javax.swing.JLabel lblSetDatCoc;
    private javax.swing.JLabel lblSetDichVu;
    private javax.swing.JLabel lblSetMaPhieu;
    private javax.swing.JLabel lblSetNgayTao;
    private javax.swing.JLabel lblSetNhanVien;
    private javax.swing.JLabel lblSetSoPhong;
    private javax.swing.JLabel lblSetThanhToan;
    private javax.swing.JLabel lblSetTienPhong;
    private javax.swing.JLabel lblSoPhong;
    private javax.swing.JLabel lblThanhToan;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblTienPhong;
    private HELPER.PanelShadow sdoChucNang;
    private HELPER.PanelShadow sdoThanhToan;
    private javax.swing.JSeparator spt_1;
    // End of variables declaration//GEN-END:variables
}
