package GUI;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import GUI.*;
import GUI.*;
import BLL.BLL_ThongKe;
import HELPER.HELPER_ChuyenDoi;
import chart.ModelPolarAreaChart;
import com.raven.chart.ModelChart;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;

/**
 *
 * @author Trung Thanh
 */
public class GUI_pnl_ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form GUI_pnl_ThongKe
     */
    public GUI_pnl_ThongKe() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoFormChinh = new HELPER.PanelShadow();
        btnThongKe = new javax.swing.JLabel();
        lblMaNhanVien = new javax.swing.JLabel();
        lblSetNgayTao = new javax.swing.JLabel();
        dateNgayThongKe2 = new com.toedter.calendar.JDateChooser();
        lblMaNhanVien1 = new javax.swing.JLabel();
        dateNgayThongKe = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        sdoFormChinh1 = new HELPER.PanelShadow();
        lblSetNgayTao1 = new javax.swing.JLabel();
        lblMaNhanVien11 = new javax.swing.JLabel();
        lblConLai = new javax.swing.JLabel();
        lblMaNhanVien2 = new javax.swing.JLabel();
        lblMaNhanVien14 = new javax.swing.JLabel();
        lblMaNhanVien15 = new javax.swing.JLabel();
        lblMaNhanVien16 = new javax.swing.JLabel();
        lblMaNhanVien18 = new javax.swing.JLabel();
        lblMaNhanVien19 = new javax.swing.JLabel();
        lblTienPhong = new javax.swing.JLabel();
        lblTienDichVu = new javax.swing.JLabel();
        lblDatCoc = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();
        lblPhiNhapKho = new javax.swing.JLabel();
        lblMaNhanVien22 = new javax.swing.JLabel();
        lblPhiChi = new javax.swing.JLabel();
        sdoFormChinh2 = new HELPER.PanelShadow();
        lblSetNgayTao2 = new javax.swing.JLabel();
        lblPhongTrong = new javax.swing.JLabel();
        lblMaNhanVien7 = new javax.swing.JLabel();
        lblDangO = new javax.swing.JLabel();
        lblMaNhanVien8 = new javax.swing.JLabel();
        lblDaTraPhong = new javax.swing.JLabel();
        lblDatTruoc = new javax.swing.JLabel();
        lblMaNhanVien10 = new javax.swing.JLabel();
        lblMaNhanVien13 = new javax.swing.JLabel();
        lblMaNhanVien20 = new javax.swing.JLabel();
        sdoFormChinh3 = new HELPER.PanelShadow();
        lblSetNgayTao3 = new javax.swing.JLabel();
        lblMaNhanVien21 = new javax.swing.JLabel();
        barChartTheoLoaiPhong = new com.raven.chart.Chart();
        sdoFormChinh4 = new HELPER.PanelShadow();
        lblSetNgayTao4 = new javax.swing.JLabel();
        lblMaNhanVien12 = new javax.swing.JLabel();
        pieChartTheoLoaiPhong = new chart.PolarAreaChart();
        sdoFormChinh5 = new HELPER.PanelShadow();
        lblSetNgayTao5 = new javax.swing.JLabel();
        lineChartKhachDenTheoGio = new raven.chart.CurveLineChart();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sdoFormChinh.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh.setShadowOpacity(0.4F);
        sdoFormChinh.setShadowSize(9);
        sdoFormChinh.setShadowType(HELPER.ShadowType.BOT);
        sdoFormChinh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThongKe.setBackground(new java.awt.Color(255, 255, 255));
        btnThongKe.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(33, 150, 243));
        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add (1).png"))); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongKeMouseClicked(evt);
            }
        });
        sdoFormChinh.add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 100, 30));

        lblMaNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblMaNhanVien.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien.setText("Đến: ");
        sdoFormChinh.add(lblMaNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 30, 30));

        lblSetNgayTao.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNgayTao.setForeground(new java.awt.Color(62, 73, 95));
        sdoFormChinh.add(lblSetNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 20));

        dateNgayThongKe2.setBackground(new java.awt.Color(255, 255, 255));
        dateNgayThongKe2.setForeground(new java.awt.Color(62, 73, 95));
        dateNgayThongKe2.setToolTipText("");
        dateNgayThongKe2.setDateFormatString("dd-MM-yyyy");
        dateNgayThongKe2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateNgayThongKe2PropertyChange(evt);
            }
        });
        sdoFormChinh.add(dateNgayThongKe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 130, 30));

        lblMaNhanVien1.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien1.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblMaNhanVien1.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien1.setText("Thống kê từ:");
        sdoFormChinh.add(lblMaNhanVien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 30));

        dateNgayThongKe.setBackground(new java.awt.Color(255, 255, 255));
        dateNgayThongKe.setForeground(new java.awt.Color(62, 73, 95));
        dateNgayThongKe.setToolTipText("");
        dateNgayThongKe.setDateFormatString("dd-MM-yyyy");
        dateNgayThongKe.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateNgayThongKePropertyChange(evt);
            }
        });
        sdoFormChinh.add(dateNgayThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 130, 30));

        add(sdoFormChinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 69));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sdoFormChinh1.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh1.setShadowOpacity(0.4F);
        sdoFormChinh1.setShadowSize(9);
        sdoFormChinh1.setShadowType(HELPER.ShadowType.BOT);
        sdoFormChinh1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetNgayTao1.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao1.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNgayTao1.setForeground(new java.awt.Color(62, 73, 95));
        sdoFormChinh1.add(lblSetNgayTao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 20));

        lblMaNhanVien11.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaNhanVien11.setText("Thu/ chi");
        sdoFormChinh1.add(lblMaNhanVien11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 30));

        lblConLai.setBackground(new java.awt.Color(255, 255, 255));
        lblConLai.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblConLai.setForeground(new java.awt.Color(97, 177, 90));
        lblConLai.setText("0");
        sdoFormChinh1.add(lblConLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 80, 30));

        lblMaNhanVien2.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien2.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien2.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien2.setText("Tiền phòng");
        sdoFormChinh1.add(lblMaNhanVien2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 30));

        lblMaNhanVien14.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien14.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien14.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien14.setText("Dịch vụ");
        sdoFormChinh1.add(lblMaNhanVien14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 60, 30));

        lblMaNhanVien15.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien15.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien15.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien15.setText("Đặt cọc");
        sdoFormChinh1.add(lblMaNhanVien15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 80, 30));

        lblMaNhanVien16.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien16.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien16.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien16.setText("Doanh thu");
        sdoFormChinh1.add(lblMaNhanVien16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 80, 30));

        lblMaNhanVien18.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien18.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien18.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien18.setText("Phí nhập kho");
        sdoFormChinh1.add(lblMaNhanVien18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 80, 30));

        lblMaNhanVien19.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien19.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien19.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien19.setText("Còn lại");
        sdoFormChinh1.add(lblMaNhanVien19, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 80, 30));

        lblTienPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblTienPhong.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblTienPhong.setForeground(new java.awt.Color(97, 177, 90));
        lblTienPhong.setText("0");
        sdoFormChinh1.add(lblTienPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 30));

        lblTienDichVu.setBackground(new java.awt.Color(255, 255, 255));
        lblTienDichVu.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblTienDichVu.setForeground(new java.awt.Color(97, 177, 90));
        lblTienDichVu.setText("0");
        sdoFormChinh1.add(lblTienDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 80, 30));

        lblDatCoc.setBackground(new java.awt.Color(255, 255, 255));
        lblDatCoc.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblDatCoc.setForeground(new java.awt.Color(97, 177, 90));
        lblDatCoc.setText("0");
        sdoFormChinh1.add(lblDatCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 80, 30));

        lblDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        lblDoanhThu.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblDoanhThu.setForeground(new java.awt.Color(97, 177, 90));
        lblDoanhThu.setText("0");
        sdoFormChinh1.add(lblDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 70, 30));

        lblPhiNhapKho.setBackground(new java.awt.Color(255, 255, 255));
        lblPhiNhapKho.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblPhiNhapKho.setForeground(new java.awt.Color(255, 51, 51));
        lblPhiNhapKho.setText("0");
        sdoFormChinh1.add(lblPhiNhapKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 80, 30));

        lblMaNhanVien22.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien22.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien22.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien22.setText("Phí chi");
        sdoFormChinh1.add(lblMaNhanVien22, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 80, 30));

        lblPhiChi.setBackground(new java.awt.Color(255, 255, 255));
        lblPhiChi.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblPhiChi.setForeground(new java.awt.Color(255, 51, 51));
        lblPhiChi.setText("0");
        sdoFormChinh1.add(lblPhiChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 50, 30));

        jPanel1.add(sdoFormChinh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 600, 130));

        sdoFormChinh2.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh2.setShadowOpacity(0.4F);
        sdoFormChinh2.setShadowSize(9);
        sdoFormChinh2.setShadowType(HELPER.ShadowType.BOT);
        sdoFormChinh2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetNgayTao2.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao2.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNgayTao2.setForeground(new java.awt.Color(62, 73, 95));
        sdoFormChinh2.add(lblSetNgayTao2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 20));

        lblPhongTrong.setBackground(new java.awt.Color(139, 229, 222));
        lblPhongTrong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhongTrong.setForeground(new java.awt.Color(255, 255, 255));
        lblPhongTrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhongTrong.setText("0");
        lblPhongTrong.setOpaque(true);
        sdoFormChinh2.add(lblPhongTrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 40, 40));

        lblMaNhanVien7.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien7.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien7.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien7.setText("Đang ở");
        sdoFormChinh2.add(lblMaNhanVien7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 80, 30));

        lblDangO.setBackground(new java.awt.Color(245, 189, 135));
        lblDangO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDangO.setForeground(new java.awt.Color(255, 255, 255));
        lblDangO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangO.setText("0");
        lblDangO.setOpaque(true);
        sdoFormChinh2.add(lblDangO, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 40, 40));

        lblMaNhanVien8.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien8.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien8.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien8.setText("Đã trả phòng");
        sdoFormChinh2.add(lblMaNhanVien8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 80, 30));

        lblDaTraPhong.setBackground(new java.awt.Color(189, 135, 245));
        lblDaTraPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDaTraPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblDaTraPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDaTraPhong.setText("0");
        lblDaTraPhong.setOpaque(true);
        sdoFormChinh2.add(lblDaTraPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 40, 40));

        lblDatTruoc.setBackground(new java.awt.Color(135, 189, 245));
        lblDatTruoc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDatTruoc.setForeground(new java.awt.Color(255, 255, 255));
        lblDatTruoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatTruoc.setText("0");
        lblDatTruoc.setOpaque(true);
        sdoFormChinh2.add(lblDatTruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 40, 40));

        lblMaNhanVien10.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien10.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien10.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien10.setText("Đặt trước");
        sdoFormChinh2.add(lblMaNhanVien10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 80, 30));

        lblMaNhanVien13.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien13.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien13.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien13.setText("Phòng trống");
        sdoFormChinh2.add(lblMaNhanVien13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 30));

        lblMaNhanVien20.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien20.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaNhanVien20.setText("Tình trạng phòng");
        sdoFormChinh2.add(lblMaNhanVien20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));

        jPanel1.add(sdoFormChinh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 130));

        sdoFormChinh3.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh3.setShadowOpacity(0.4F);
        sdoFormChinh3.setShadowSize(9);
        sdoFormChinh3.setShadowType(HELPER.ShadowType.BOT);
        sdoFormChinh3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetNgayTao3.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao3.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNgayTao3.setForeground(new java.awt.Color(62, 73, 95));
        sdoFormChinh3.add(lblSetNgayTao3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 20));

        lblMaNhanVien21.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien21.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaNhanVien21.setText("Theo loại phòng");
        sdoFormChinh3.add(lblMaNhanVien21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));
        sdoFormChinh3.add(barChartTheoLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 530, -1));

        jPanel1.add(sdoFormChinh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 550, 450));

        sdoFormChinh4.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh4.setShadowOpacity(0.4F);
        sdoFormChinh4.setShadowSize(9);
        sdoFormChinh4.setShadowType(HELPER.ShadowType.BOT);
        sdoFormChinh4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetNgayTao4.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao4.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNgayTao4.setForeground(new java.awt.Color(62, 73, 95));
        sdoFormChinh4.add(lblSetNgayTao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 20));

        lblMaNhanVien12.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaNhanVien12.setText("Theo loại phòng");
        sdoFormChinh4.add(lblMaNhanVien12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));
        sdoFormChinh4.add(pieChartTheoLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 580, 380));

        jPanel1.add(sdoFormChinh4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, 600, 450));

        sdoFormChinh5.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh5.setShadowOpacity(0.4F);
        sdoFormChinh5.setShadowSize(9);
        sdoFormChinh5.setShadowType(HELPER.ShadowType.BOT);
        sdoFormChinh5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetNgayTao5.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao5.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNgayTao5.setForeground(new java.awt.Color(62, 73, 95));
        sdoFormChinh5.add(lblSetNgayTao5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 20));

        lineChartKhachDenTheoGio.setBackground(new java.awt.Color(0, 0, 0));
        lineChartKhachDenTheoGio.setForeground(new java.awt.Color(0, 0, 0));
        lineChartKhachDenTheoGio.setFillColor(true);
        sdoFormChinh5.add(lineChartKhachDenTheoGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 1080, 380));

        jPanel1.add(sdoFormChinh5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1140, 480));

        jScrollPane1.setViewportView(jPanel1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1150, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void dateNgayThongKe2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateNgayThongKe2PropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_dateNgayThongKe2PropertyChange

    private void btnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseClicked
    barChart();
    thongKeTinhTrangPhong();
    lineChart();
    pieChart();
    ThongKeNguonTienTrongNgay();
       
    }//GEN-LAST:event_btnThongKeMouseClicked

    private void dateNgayThongKePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateNgayThongKePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dateNgayThongKePropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.Chart barChartTheoLoaiPhong;
    private javax.swing.JLabel btnThongKe;
    private com.toedter.calendar.JDateChooser dateNgayThongKe;
    private com.toedter.calendar.JDateChooser dateNgayThongKe2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConLai;
    private javax.swing.JLabel lblDaTraPhong;
    private javax.swing.JLabel lblDangO;
    private javax.swing.JLabel lblDatCoc;
    private javax.swing.JLabel lblDatTruoc;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblMaNhanVien;
    private javax.swing.JLabel lblMaNhanVien1;
    private javax.swing.JLabel lblMaNhanVien10;
    private javax.swing.JLabel lblMaNhanVien11;
    private javax.swing.JLabel lblMaNhanVien12;
    private javax.swing.JLabel lblMaNhanVien13;
    private javax.swing.JLabel lblMaNhanVien14;
    private javax.swing.JLabel lblMaNhanVien15;
    private javax.swing.JLabel lblMaNhanVien16;
    private javax.swing.JLabel lblMaNhanVien18;
    private javax.swing.JLabel lblMaNhanVien19;
    private javax.swing.JLabel lblMaNhanVien2;
    private javax.swing.JLabel lblMaNhanVien20;
    private javax.swing.JLabel lblMaNhanVien21;
    private javax.swing.JLabel lblMaNhanVien22;
    private javax.swing.JLabel lblMaNhanVien7;
    private javax.swing.JLabel lblMaNhanVien8;
    private javax.swing.JLabel lblPhiChi;
    private javax.swing.JLabel lblPhiNhapKho;
    private javax.swing.JLabel lblPhongTrong;
    private javax.swing.JLabel lblSetNgayTao;
    private javax.swing.JLabel lblSetNgayTao1;
    private javax.swing.JLabel lblSetNgayTao2;
    private javax.swing.JLabel lblSetNgayTao3;
    private javax.swing.JLabel lblSetNgayTao4;
    private javax.swing.JLabel lblSetNgayTao5;
    private javax.swing.JLabel lblTienDichVu;
    private javax.swing.JLabel lblTienPhong;
    private raven.chart.CurveLineChart lineChartKhachDenTheoGio;
    private chart.PolarAreaChart pieChartTheoLoaiPhong;
    private HELPER.PanelShadow sdoFormChinh;
    private HELPER.PanelShadow sdoFormChinh1;
    private HELPER.PanelShadow sdoFormChinh2;
    private HELPER.PanelShadow sdoFormChinh3;
    private HELPER.PanelShadow sdoFormChinh4;
    private HELPER.PanelShadow sdoFormChinh5;
    // End of variables declaration//GEN-END:variables
void init(){
    Date date = new Date();
    dateNgayThongKe.setDate(date);
    dateNgayThongKe2.setDate(date);
    
    barChartTheoLoaiPhong.addLegend("Phòng trống", new Color(139, 229, 222));
    barChartTheoLoaiPhong.addLegend("Đang ở", new Color(245, 189, 135));
    barChartTheoLoaiPhong.addLegend("Phòng trả", new Color(189, 135, 245));
    barChartTheoLoaiPhong.addLegend("Đặt trước", new Color(135, 189, 245));
    
    lineChartKhachDenTheoGio.setTitle("Số lượng khách đến theo khung giờ");
        //random color line chart  
//    Random rd = new Random();
//        int nb = rd.nextInt(3);
//        if(nb==0) lineChartKhachDenTheoGio.addLegend("Số lượng", Color.decode("#7b4397"), Color.decode("#dc2430"));
//        if(nb==1) lineChartKhachDenTheoGio.addLegend("Số lượng", Color.decode("#e65c00"), Color.decode("#F9D423"));
            lineChartKhachDenTheoGio.addLegend("Số lượng", Color.decode("#0099F7"), Color.decode("#F11712"));
     
    barChart();
    pieChart();
    lineChart();
    thongKeTinhTrangPhong();
    ThongKeNguonTienTrongNgay();
}

void barChart()
{
        barChartTheoLoaiPhong.clear();
ArrayList<Object[]> arrList = BLL_ThongKe.ThongKeTinhTrangLoaiPhong(dateNgayThongKe2.getDate());
        for(int i =0; i< arrList.size(); i++)
        {
            Object[] obj = arrList.get(i);
            barChartTheoLoaiPhong.addData(new ModelChart(obj[0].toString(), new int[]{(int)obj[1], (int)obj[2], (int)obj[3],(int)obj[4]}));
        }        
        barChartTheoLoaiPhong.start();     
}

void pieChart()
{
    ArrayList<Object[]> arrList = BLL_ThongKe.TienLoaiPhongKiemTrongNgay(dateNgayThongKe.getDate(), dateNgayThongKe2.getDate());
    pieChartTheoLoaiPhong.clear();
    for(Object[] obj : arrList)
    {
        pieChartTheoLoaiPhong.addItem(new ModelPolarAreaChart(BLL_ThongKe.randomColor(), obj[0].toString(), (double) obj[1]));
    }
    pieChartTheoLoaiPhong.start();
}

void lineChart()
{
        ArrayList<Object[]> arrList = BLL_ThongKe.SLKhachVaoTheoGio(dateNgayThongKe.getDate(), dateNgayThongKe2.getDate());
        lineChartKhachDenTheoGio.clear();
        for (int i = arrList.size() - 1; i >= 0; i--) {
                Object[] obj = arrList.get(i);
                lineChartKhachDenTheoGio.addData(new raven.chart.ModelChart(obj[0].toString()+ " Giờ", new double[]{(double)obj[1]}));
            }        
        lineChartKhachDenTheoGio.start();    
}

void ThongKeNguonTienTrongNgay()
{
    ArrayList<Double> arrList = BLL_ThongKe.NguonTienTrongNgay(dateNgayThongKe.getDate(), dateNgayThongKe2.getDate());
    lblTienPhong.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(0))+"K");
    lblTienDichVu.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(1))+"K");
    lblDatCoc.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(2))+"K");
    lblDoanhThu.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(3))+"K");
    lblPhiChi.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(4))+"K");
    lblPhiNhapKho.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(5))+"K");
    lblConLai.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(6))+"K");
}

void thongKeTinhTrangPhong()
{
    ArrayList<Object> arrList = BLL_ThongKe.ThongKeTinhTrangPhong(dateNgayThongKe2.getDate());

    lblPhongTrong.setText(arrList.get(0).toString());
    lblDangO.setText(arrList.get(1).toString());
    lblDaTraPhong.setText(arrList.get(2).toString());
    lblDatTruoc.setText(arrList.get(3).toString());  
}
}
