/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_TaiKhoan;
import DAL.DAL_TaiKhoan;
import DTO.DTO_TaiKhoan;
import java.awt.Color;
import java.awt.Desktop;
import java.net.URI;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_ChangePassWord extends javax.swing.JPanel {

    public boolean isPassword = false;
    public boolean isConfirmPassword = false;

    /**
     * Creates new form GUI_pnlDangKi
     */
    public GUI_pnl_ChangePassWord() {
        initComponents();
        load(psdMatKhau, psdXacThucMatKhau);
    }

    public void load(JPasswordField psd, JPasswordField psdConfirm) {
        psd.setText("Nhập Mật Khẩu");
        psd.setEchoChar((char) 0);
        psd.setForeground(new Color(153, 153, 153));
        psd.setText("Nhập Lại Mật Khẩu");
        psdConfirm.setEchoChar((char) 0);
        psdConfirm.setForeground(new Color(153, 153, 153));
    }

    public void focusPassWord(JPasswordField psd, String getText, String setText, int r, int g, int b, char c) {
        if (String.valueOf(psd.getPassword()).equals(getText)) {
            psd.setForeground(new Color(r, g, b));
            psd.setText(setText);
            psd.setEchoChar(c);
        }
    }

    public void isPassword(JPasswordField psd, JLabel lbl) {
        if (!isPassword) {
            psd.setEchoChar((char) 0);
            isPassword = true;
            lbl.setIcon(new ImageIcon("src/IMG/hidden.png"));

        } else {
            psd.setEchoChar('*');
            isPassword = false;
            lbl.setIcon(new ImageIcon("src/IMG/hidden (1).png"));
        }
    }

    public void isConfirmPassword(JPasswordField psd, JLabel lbl) {
        if (!isConfirmPassword) {
            psd.setEchoChar((char) 0);
            isConfirmPassword = true;
            lbl.setIcon(new ImageIcon("src/IMG/hidden.png"));

        } else {
            psd.setEchoChar('*');
            isConfirmPassword = false;
            lbl.setIcon(new ImageIcon("src/IMG/hidden (1).png"));
        }
    }

    public void resetPassword() {
        if (psdMatKhau.getPassword().equals(null) || psdXacThucMatKhau.getPassword().equals(null)) {
            JOptionPane.showMessageDialog(this, "Dữ Liệu Không Được Để Trống ???");
        } else if (!String.valueOf(psdMatKhau.getPassword()).equals(String.valueOf(psdXacThucMatKhau.getPassword()))) {
            JOptionPane.showMessageDialog(this, "Không Khớp Mật Khẩu ???");
        } else {
            DAL_TaiKhoan.editMatKhau(String.valueOf(psdMatKhau.getPassword()), GUI_pnl_CheckMail.mail);
            JOptionPane.showMessageDialog(this, "Cập Nhật Hoàn Tất !!!");
            GUI_frm_Login.pnlLogin.removeAll();
            GUI_frm_Login.pnlLogin.add(new GUI_pnl_DangNhap().pnlDangNhap);
            GUI_frm_Login.pnlLogin.validate();
            GUI_frm_Login.pnlLogin.repaint();
        }
    }

    public void setBackground_78_87_103(JLabel lbl) {
        lbl.setBackground(new Color(78, 87, 103));
    }

    public void setBackground_62_73_95(JLabel lbl) {
        lbl.setBackground(new Color(62, 73, 95));
    }

    public void setForeground_33_150_243(JLabel lbl) {
        lbl.setForeground(new Color(33, 150, 243));
    }

    public void setForeground_62_73_95(JLabel lbl) {
        lbl.setForeground(new Color(62, 73, 95));
    }

    public void showFanPage() {
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new URI("https://www.facebook.com/MrPii.2k3"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void showDisCord() {
        Desktop desktop = Desktop.getDesktop();
        try {
            desktop.browse(new URI("https://discord.com/channels/902461485291274281/902461485798793217"));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void exit() {
        int choice = JOptionPane.showConfirmDialog(null, "Bạn Có Muốn Thoát Chương Trình ???", "Thoát", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlChangePassWord = new javax.swing.JPanel();
        lblShowHiddenMatKhau = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        psdMatKhau = new javax.swing.JPasswordField();
        lblIconMatKhau = new javax.swing.JLabel();
        lblHoanThanh = new javax.swing.JLabel();
        lblIconXacThucMatKhau = new javax.swing.JLabel();
        psdXacThucMatKhau = new javax.swing.JPasswordField();
        lblShowHiddenXacThucMatKhau = new javax.swing.JLabel();
        lblHoTro = new javax.swing.JLabel();
        lblSetHoTro = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        lblSetWebsite = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 450));
        setPreferredSize(new java.awt.Dimension(400, 450));

        pnlChangePassWord.setBackground(new java.awt.Color(255, 255, 255));
        pnlChangePassWord.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(33, 150, 243)));
        pnlChangePassWord.setMinimumSize(new java.awt.Dimension(400, 450));
        pnlChangePassWord.setPreferredSize(new java.awt.Dimension(400, 450));
        pnlChangePassWord.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowHiddenMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        lblShowHiddenMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hidden (1).png"))); // NOI18N
        lblShowHiddenMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(62, 73, 95)));
        lblShowHiddenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowHiddenMatKhauMouseClicked(evt);
            }
        });
        pnlChangePassWord.add(lblShowHiddenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 30, 30));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close (4).png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        pnlChangePassWord.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 20, 20));

        psdMatKhau.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        psdMatKhau.setForeground(new java.awt.Color(62, 73, 95));
        psdMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(62, 73, 95)));
        psdMatKhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                psdMatKhauFocusLost(evt);
            }
        });
        psdMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psdMatKhauMouseClicked(evt);
            }
        });
        pnlChangePassWord.add(psdMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 270, 30));

        lblIconMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        lblIconMatKhau.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblIconMatKhau.setForeground(new java.awt.Color(153, 153, 153));
        lblIconMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/padlock.png"))); // NOI18N
        pnlChangePassWord.add(lblIconMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 30, 30));

        lblHoanThanh.setBackground(new java.awt.Color(62, 73, 95));
        lblHoanThanh.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblHoanThanh.setForeground(new java.awt.Color(255, 255, 255));
        lblHoanThanh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHoanThanh.setText("HOÀN THÀNH");
        lblHoanThanh.setOpaque(true);
        lblHoanThanh.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblHoanThanhMouseMoved(evt);
            }
        });
        lblHoanThanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHoanThanhMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblHoanThanhMouseExited(evt);
            }
        });
        pnlChangePassWord.add(lblHoanThanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 300, 40));

        lblIconXacThucMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        lblIconXacThucMatKhau.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblIconXacThucMatKhau.setForeground(new java.awt.Color(153, 153, 153));
        lblIconXacThucMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/lock.png"))); // NOI18N
        pnlChangePassWord.add(lblIconXacThucMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 30, 30));

        psdXacThucMatKhau.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        psdXacThucMatKhau.setForeground(new java.awt.Color(62, 73, 95));
        psdXacThucMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(62, 73, 95)));
        psdXacThucMatKhau.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                psdXacThucMatKhauFocusLost(evt);
            }
        });
        psdXacThucMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                psdXacThucMatKhauMouseClicked(evt);
            }
        });
        pnlChangePassWord.add(psdXacThucMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 270, 30));

        lblShowHiddenXacThucMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        lblShowHiddenXacThucMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hidden (1).png"))); // NOI18N
        lblShowHiddenXacThucMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(62, 73, 95)));
        lblShowHiddenXacThucMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowHiddenXacThucMatKhauMouseClicked(evt);
            }
        });
        pnlChangePassWord.add(lblShowHiddenXacThucMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 30, 30));

        lblHoTro.setBackground(new java.awt.Color(255, 255, 255));
        lblHoTro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblHoTro.setForeground(new java.awt.Color(153, 153, 153));
        lblHoTro.setText("Hỗ Trợ:");
        pnlChangePassWord.add(lblHoTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, 20));

        lblSetHoTro.setBackground(new java.awt.Color(255, 255, 255));
        lblSetHoTro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetHoTro.setForeground(new java.awt.Color(62, 73, 95));
        lblSetHoTro.setText("Game2K");
        lblSetHoTro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSetHoTroMouseMoved(evt);
            }
        });
        lblSetHoTro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSetHoTroMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSetHoTroMouseExited(evt);
            }
        });
        pnlChangePassWord.add(lblSetHoTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, 20));

        lblWebsite.setBackground(new java.awt.Color(255, 255, 255));
        lblWebsite.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblWebsite.setForeground(new java.awt.Color(153, 153, 153));
        lblWebsite.setText("Website:");
        pnlChangePassWord.add(lblWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, 20));

        lblSetWebsite.setBackground(new java.awt.Color(255, 255, 255));
        lblSetWebsite.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetWebsite.setForeground(new java.awt.Color(62, 73, 95));
        lblSetWebsite.setText("MrPii.2k3");
        lblSetWebsite.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblSetWebsiteMouseMoved(evt);
            }
        });
        lblSetWebsite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSetWebsiteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSetWebsiteMouseExited(evt);
            }
        });
        pnlChangePassWord.add(lblSetWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 420, -1, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChangePassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlChangePassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblHoanThanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoanThanhMouseClicked
        // TODO add your handling code here:
        resetPassword();
    }//GEN-LAST:event_lblHoanThanhMouseClicked

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        exit();
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblShowHiddenMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowHiddenMatKhauMouseClicked
        // TODO add your handling code here:
        isPassword(psdMatKhau, lblShowHiddenMatKhau);
    }//GEN-LAST:event_lblShowHiddenMatKhauMouseClicked

    private void lblShowHiddenXacThucMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowHiddenXacThucMatKhauMouseClicked
        // TODO add your handling code here:
        isConfirmPassword(psdXacThucMatKhau, lblShowHiddenXacThucMatKhau);
    }//GEN-LAST:event_lblShowHiddenXacThucMatKhauMouseClicked

    private void psdMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psdMatKhauMouseClicked
        // TODO add your handling code here:
        focusPassWord(psdMatKhau, "Nhập Mật Khẩu", "", 62, 73, 95, '*');
    }//GEN-LAST:event_psdMatKhauMouseClicked

    private void psdXacThucMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_psdXacThucMatKhauMouseClicked
        // TODO add your handling code here:
        focusPassWord(psdXacThucMatKhau, "Nhập Lại Mật Khẩu", "", 62, 73, 95, '*');
    }//GEN-LAST:event_psdXacThucMatKhauMouseClicked

    private void psdMatKhauFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_psdMatKhauFocusLost
        // TODO add your handling code here:
        focusPassWord(psdMatKhau, "", "Nhập Mật Khẩu", 153, 153, 153, (char) 0);
    }//GEN-LAST:event_psdMatKhauFocusLost

    private void psdXacThucMatKhauFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_psdXacThucMatKhauFocusLost
        // TODO add your handling code here:
        focusPassWord(psdXacThucMatKhau, "", "Nhập Lại Mật Khẩu", 153, 153, 153, (char) 0);
    }//GEN-LAST:event_psdXacThucMatKhauFocusLost

    private void lblHoanThanhMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoanThanhMouseMoved
        // TODO add your handling code here:
        setBackground_78_87_103(lblHoanThanh);
    }//GEN-LAST:event_lblHoanThanhMouseMoved

    private void lblHoanThanhMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHoanThanhMouseExited
        // TODO add your handling code here:
        setBackground_62_73_95(lblHoanThanh);
    }//GEN-LAST:event_lblHoanThanhMouseExited

    private void lblSetHoTroMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetHoTroMouseMoved
        // TODO add your handling code here:
        setForeground_33_150_243(lblSetHoTro);
    }//GEN-LAST:event_lblSetHoTroMouseMoved

    private void lblSetHoTroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetHoTroMouseClicked
        // TODO add your handling code here:
        showDisCord();
    }//GEN-LAST:event_lblSetHoTroMouseClicked

    private void lblSetHoTroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetHoTroMouseExited
        // TODO add your handling code here:
        setForeground_62_73_95(lblSetHoTro);
    }//GEN-LAST:event_lblSetHoTroMouseExited

    private void lblSetWebsiteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetWebsiteMouseMoved
        // TODO add your handling code here:
        setForeground_33_150_243(lblSetWebsite);
    }//GEN-LAST:event_lblSetWebsiteMouseMoved

    private void lblSetWebsiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetWebsiteMouseClicked
        // TODO add your handling code here:
        showFanPage();
    }//GEN-LAST:event_lblSetWebsiteMouseClicked

    private void lblSetWebsiteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetWebsiteMouseExited
        // TODO add your handling code here:
        setForeground_62_73_95(lblSetWebsite);
    }//GEN-LAST:event_lblSetWebsiteMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHoTro;
    private javax.swing.JLabel lblHoanThanh;
    private javax.swing.JLabel lblIconMatKhau;
    private javax.swing.JLabel lblIconXacThucMatKhau;
    private javax.swing.JLabel lblSetHoTro;
    private javax.swing.JLabel lblSetWebsite;
    private javax.swing.JLabel lblShowHiddenMatKhau;
    private javax.swing.JLabel lblShowHiddenXacThucMatKhau;
    private javax.swing.JLabel lblWebsite;
    public javax.swing.JPanel pnlChangePassWord;
    private javax.swing.JPasswordField psdMatKhau;
    private javax.swing.JPasswordField psdXacThucMatKhau;
    // End of variables declaration//GEN-END:variables
}
