/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_DichVu;
import BLL.BLL_HangMucChi;
import BLL.BLL_HoaDon;
import BLL.BLL_MaTenLoai;
import BLL.BLL_Phong;
import BLL.BLL_SoDoPhong;
import BLL.BLL_TaiKhoan;
import BLL.BLL_ThuePhong;
import DAL.DAL_DichVu;
import DAL.DAL_ThuePhong;
import DTO.DTO_HangMucChi;
import DTO.DTO_HoaDon;
import DTO.DTO_Phong;
import DTO.DTO_SoTang;
import DTO.DTO_ThuePhong;
import HELPER.HELPER_ChuyenDoi;
import HELPER.HELPER_SetMa;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author CherryCe
 */
public class GUI_dal_ChuyenPhong extends javax.swing.JDialog {

    public static String maTang;
    public static int index;
    public static int setHeight;
    public static JDialog dal = null;
    public static String maPhong;
    public static String maPhieuThue;
    public static String maNhanVien;
    public static Date ngayTao;
    public static Date ngayDen;
    public static Date ngayDi;
    public static String CMND;
    public static String tenKhachHang;
    public static int soLuong;
    public static String ghiChu;
    public static int tienCoc;
    public static int giamGia;
    public static byte[] hinhAnh;
    public static String maPhuongThuc;
    public static int trangThaiThanhToan;
    public static int conLai;

    /**
     * Creates new form GUI_dalThongTinPhong
     */
    public GUI_dal_ChuyenPhong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadPhong();
        loadTenTang();
        search();
        loadThuePhong();
        dal = this;
    }

    public void loadPhong() {
        if (!GUI_pnl_SoDoPhong.isSelectPhong) {
            lblSoPhongDi.setText(BLL_SoDoPhong.selectChuyenPhong(GUI_pnl_ChiTietPhong.indexPosition + 1));
        } else {
            lblSoPhongDi.setText(BLL_SoDoPhong.selectChuyenPhong(GUI_pnl_SoDoPhong.maTang, GUI_pnl_ChiTietPhong.indexPosition + 1));
        }
        lblSetNgayDen.setText(BLL_ThuePhong.selectChuyenPhong(BLL_MaTenLoai.findMaPhong(lblSoPhongDi.getText().substring(0, 3)), "NgayDen"));
        lblSetNgayDi.setText(BLL_ThuePhong.selectChuyenPhong(BLL_MaTenLoai.findMaPhong(lblSoPhongDi.getText().substring(0, 3)), "NgayDi"));
    }

    public void loadTenTang() {
        ArrayList<DTO_SoTang> array = BLL_MaTenLoai.selectTenTang();
        BLL_MaTenLoai.loadTenTang(array, cboTang);
    }

    public void search() {
        if (BLL_Phong.countSearchChuyenPhong(maTang) % 4 == 0) {
            setHeight = BLL_Phong.countSearchChuyenPhong(maTang) / 4;
        } else {
            setHeight = (BLL_Phong.countSearchChuyenPhong(maTang) / 4) + 1;
        }
        pnlDanhSachPhong.setPreferredSize(new Dimension(710, 150 * setHeight));
        pnlDanhSachPhong.removeAll();
        for (int i = 1; i <= BLL_Phong.countSearchChuyenPhong(maTang); i++) {
            index = i;
            pnlDanhSachPhong.add(new GUI_pnl_ChuyenPhong().pnlChuyenPhong);
        }
        pnlDanhSachPhong.validate();
        pnlDanhSachPhong.repaint();
    }

    public void loadThuePhong() {
        ArrayList<DTO_ThuePhong> arrayThuePhong = BLL_ThuePhong.select(BLL_MaTenLoai.findMaPhong(lblSoPhongDi.getText().substring(0, 3)));
        BLL_ThuePhong.load(arrayThuePhong);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoChuyenPhong = new HELPER.PanelShadow();
        lblChuyenPhong = new javax.swing.JLabel();
        cboTang = new javax.swing.JComboBox<>();
        lblExit = new javax.swing.JLabel();
        scrDanhSachPhong = new javax.swing.JScrollPane();
        pnlDanhSachPhong = new javax.swing.JPanel();
        sdoChuyenTuPhong = new HELPER.PanelShadow();
        lblSetNgayDi = new javax.swing.JLabel();
        lblNgayDen = new javax.swing.JLabel();
        lblSetNgayDen = new javax.swing.JLabel();
        lblNgayDi = new javax.swing.JLabel();
        lblChuyenTuPhong = new javax.swing.JLabel();
        lblSoPhongDi = new javax.swing.JLabel();
        sdoChuyenToiPhong = new HELPER.PanelShadow();
        lblGhiChu = new javax.swing.JLabel();
        lblSoPhongDen = new javax.swing.JLabel();
        lblChuyenToiPhong = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        lblChuyen = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 600));
        setUndecorated(true);

        sdoChuyenPhong.setBackground(new java.awt.Color(255, 255, 255));
        sdoChuyenPhong.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(33, 150, 243)));
        sdoChuyenPhong.setMinimumSize(new java.awt.Dimension(750, 600));
        sdoChuyenPhong.setPreferredSize(new java.awt.Dimension(750, 600));
        sdoChuyenPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChuyenPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblChuyenPhong.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblChuyenPhong.setForeground(new java.awt.Color(62, 73, 95));
        lblChuyenPhong.setText("CHUYỂN PHÒNG");
        sdoChuyenPhong.add(lblChuyenPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 14, 150, 30));

        cboTang.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboTang.setForeground(new java.awt.Color(62, 73, 95));
        cboTang.setToolTipText("");
        cboTang.setBorder(null);
        cboTang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboTangItemStateChanged(evt);
            }
        });
        sdoChuyenPhong.add(cboTang, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 16, 100, -1));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close (1).png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        sdoChuyenPhong.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 30, 30));

        scrDanhSachPhong.setBackground(new java.awt.Color(255, 255, 255));
        scrDanhSachPhong.setBorder(null);
        scrDanhSachPhong.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlDanhSachPhong.setBackground(new java.awt.Color(255, 255, 255));
        pnlDanhSachPhong.setMinimumSize(new java.awt.Dimension(710, 380));
        pnlDanhSachPhong.setPreferredSize(new java.awt.Dimension(710, 380));
        pnlDanhSachPhong.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 20));
        scrDanhSachPhong.setViewportView(pnlDanhSachPhong);

        sdoChuyenPhong.add(scrDanhSachPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 710, 380));

        sdoChuyenTuPhong.setBackground(new java.awt.Color(255, 255, 255));
        sdoChuyenTuPhong.setMinimumSize(new java.awt.Dimension(730, 70));
        sdoChuyenTuPhong.setShadowOpacity(0.3F);
        sdoChuyenTuPhong.setShadowType(HELPER.ShadowType.BOT);
        sdoChuyenTuPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetNgayDi.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayDi.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetNgayDi.setForeground(new java.awt.Color(255, 142, 113));
        sdoChuyenTuPhong.add(lblSetNgayDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 100, 20));

        lblNgayDen.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayDen.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayDen.setForeground(new java.awt.Color(153, 153, 153));
        lblNgayDen.setText("Ngày Đến");
        sdoChuyenTuPhong.add(lblNgayDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 20));

        lblSetNgayDen.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayDen.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetNgayDen.setForeground(new java.awt.Color(255, 142, 113));
        sdoChuyenTuPhong.add(lblSetNgayDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 100, 20));

        lblNgayDi.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayDi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayDi.setForeground(new java.awt.Color(153, 153, 153));
        lblNgayDi.setText("Ngày Đi");
        sdoChuyenTuPhong.add(lblNgayDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, 20));

        lblChuyenTuPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblChuyenTuPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblChuyenTuPhong.setForeground(new java.awt.Color(153, 153, 153));
        lblChuyenTuPhong.setText("Chuyển Từ Phòng");
        sdoChuyenTuPhong.add(lblChuyenTuPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        lblSoPhongDi.setBackground(new java.awt.Color(255, 255, 255));
        lblSoPhongDi.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSoPhongDi.setForeground(new java.awt.Color(255, 142, 113));
        sdoChuyenTuPhong.add(lblSoPhongDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 160, 20));

        sdoChuyenPhong.add(sdoChuyenTuPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 730, 70));

        sdoChuyenToiPhong.setBackground(new java.awt.Color(255, 255, 255));
        sdoChuyenToiPhong.setMinimumSize(new java.awt.Dimension(730, 70));
        sdoChuyenToiPhong.setShadowOpacity(0.3F);
        sdoChuyenToiPhong.setShadowType(HELPER.ShadowType.BOT);
        sdoChuyenToiPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGhiChu.setBackground(new java.awt.Color(255, 255, 255));
        lblGhiChu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(153, 153, 153));
        lblGhiChu.setText("Ghi Chú");
        sdoChuyenToiPhong.add(lblGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, -1, 20));

        lblSoPhongDen.setBackground(new java.awt.Color(255, 255, 255));
        lblSoPhongDen.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSoPhongDen.setForeground(new java.awt.Color(97, 177, 90));
        sdoChuyenToiPhong.add(lblSoPhongDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 160, 20));

        lblChuyenToiPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblChuyenToiPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblChuyenToiPhong.setForeground(new java.awt.Color(153, 153, 153));
        lblChuyenToiPhong.setText("Chuyển Tới Phòng");
        sdoChuyenToiPhong.add(lblChuyenToiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 20));

        txtGhiChu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(62, 73, 90));
        txtGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        sdoChuyenToiPhong.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 190, -1));

        lblChuyen.setBackground(new java.awt.Color(255, 255, 255));
        lblChuyen.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblChuyen.setForeground(new java.awt.Color(33, 150, 243));
        lblChuyen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/circle-of-two-clockwise-arrows-rotation.png"))); // NOI18N
        lblChuyen.setText("Chuyển");
        lblChuyen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblChuyenMouseClicked(evt);
            }
        });
        sdoChuyenToiPhong.add(lblChuyen, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 80, 20));

        sdoChuyenPhong.add(sdoChuyenToiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 730, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoChuyenPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoChuyenPhong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblExitMouseClicked

    private void cboTangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboTangItemStateChanged
        // TODO add your handling code here:
        maTang = BLL_MaTenLoai.findMaTang(String.valueOf(cboTang.getSelectedItem()));
        search();
    }//GEN-LAST:event_cboTangItemStateChanged

    private void lblChuyenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblChuyenMouseClicked
        // TODO add your handling code here:
        if (lblSoPhongDen.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dữ Liệu Không Được Để Trống !!!");
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Chuyển Từ Phòng " + lblSoPhongDi.getText().substring(0, 3) + " Đến Phòng " + lblSoPhongDen.getText().substring(0, 3) + "\n" + "Xác Nhận Chuyển Phòng ???", "Chuyển Phòng", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                DTO_ThuePhong thuePhong = new DTO_ThuePhong(BLL_MaTenLoai.findMaPhong(lblSoPhongDen.getText().substring(0, 3)), HELPER_SetMa.setMaDateTime("PT"), BLL_TaiKhoan.selectMaNhanVien(GUI_pnl_DangNhap.taiKhoan), HELPER_ChuyenDoi.getNgayDate("dd-MM-yy HH:mm", HELPER_ChuyenDoi.getTimeNow("dd-MM-yy HH:mm")), HELPER_ChuyenDoi.getNgayDate("dd-MM-yyyy HH:mm", HELPER_ChuyenDoi.getTimeNow("dd-MM-yyyy HH:mm")), null, CMND, tenKhachHang, soLuong, "Chuyển Từ Phòng " + lblSoPhongDi.getText().substring(0, 3) + ", " + ghiChu, 0, 0 - conLai, hinhAnh, maPhuongThuc, trangThaiThanhToan);
                BLL_ThuePhong.addThuePhong(thuePhong);
                DTO_ThuePhong thanhToan = new DTO_ThuePhong(BLL_MaTenLoai.findMaPhong(lblSoPhongDi.getText().substring(0, 3)), maPhieuThue, maNhanVien, ngayTao, ngayDen, HELPER_ChuyenDoi.getNgayDate("dd-MM-yyyy HH:mm", HELPER_ChuyenDoi.getTimeNow("dd-MM-yyyy HH:mm")), CMND, tenKhachHang, soLuong, "Chuyển Đến Phòng " + lblSoPhongDen.getText().substring(0, 3) + ", " + ghiChu, tienCoc, giamGia, hinhAnh, maPhuongThuc, trangThaiThanhToan);
                BLL_ThuePhong.addThanhToan(thanhToan);
                if (!GUI_pnl_SoDoPhong.isSelectPhong) {
                    GUI_pnl_SoDoPhong.load();
                } else {
                    GUI_pnl_SoDoPhong.search();
                }
                GUI_dal_ChuyenPhong.dal.dispose();
            }
            return;
        }
    }//GEN-LAST:event_lblChuyenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ChuyenPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ChuyenPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ChuyenPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ChuyenPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI_dal_ChuyenPhong dialog = new GUI_dal_ChuyenPhong(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboTang;
    private javax.swing.JLabel lblChuyen;
    private javax.swing.JLabel lblChuyenPhong;
    private javax.swing.JLabel lblChuyenToiPhong;
    private javax.swing.JLabel lblChuyenTuPhong;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblNgayDen;
    private javax.swing.JLabel lblNgayDi;
    private javax.swing.JLabel lblSetNgayDen;
    private javax.swing.JLabel lblSetNgayDi;
    public static javax.swing.JLabel lblSoPhongDen;
    private javax.swing.JLabel lblSoPhongDi;
    public static javax.swing.JPanel pnlDanhSachPhong;
    private javax.swing.JScrollPane scrDanhSachPhong;
    private HELPER.PanelShadow sdoChuyenPhong;
    private HELPER.PanelShadow sdoChuyenToiPhong;
    private HELPER.PanelShadow sdoChuyenTuPhong;
    private javax.swing.JTextField txtGhiChu;
    // End of variables declaration//GEN-END:variables
}
